services:
  redis:
    image: redis:latest
    container_name: redis-room-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    environment:
      - REDIS_PASSWORD=admin
    command: redis-server --requirepass admin

volumes:
  redis-data:
    driver: local