version: '3.8'
services:
  app:
    image: node:22.11
    container_name: derdo-front
    ports:
      - "3000:3000"
    volumes:
      - ./web
    working_dir: /usr/src/app
    command: ["npm", "start"]
    restart: unless-stopped

  server:
    image: node:22.11
    container_name: derdo-server
    ports:
      - "3001:3001"
    volumes:
      - ./server
    working_dir: ./server
    command: ["npm", "start"]
    restart: unless-stopped
    depends_on:
      - redis
  
  redis: 
    image: redis:latest
    container_name: derdo-redis
    ports: 
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped


volumes:
  redis-data: 
    driver: local
