name: derdo
services:
  redis: 
    image: redis:latest
    container_name: derdo-room-redis
    ports: 
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped


volumes:
  redis-data: 
    driver: local